import 'package:flutter/material.dart';

class CallModel {
  final String name;
  final Icon callType;
  final IconData iconType;
  final IconData i_iconType;
  final String i_time;
  final String i_call;
  final String i_repled;
  final String time;
  final String day;
  final String call;
  final String repled;
  final String about;
  final String avatar;

  CallModel({
    required this.name,
    required this.day,
    required this.i_time,
    required this.call,
    required this.i_call,
    required this.repled,
    required this.i_repled,
    required this.callType,
    required this.iconType,
    required this.i_iconType,
    required this.time,
    required this.about,
    required this.avatar,
  });

  static Icon callRecived = const Icon(
    Icons.call_received,
    color: Colors.green,
  );
  static Icon callMissed = const Icon(
    Icons.call_missed,
    color: Colors.red,
  );

  static const IconData Recived = Icons.call_received; // IconData
  static const IconData Missed = Icons.call_missed; // IconData
}

List<CallModel> callData = [
  CallModel(
    name: 'Syed Hassan',
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    time: '10:20',
    day: "Today",
    repled: "Answered",
    call: "Outgoing",
    about: "hi there",
    avatar: "images/a.jpg",
  ),
  CallModel(
    name: 'Alice',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '09:15',
    day: "Yesterday",
    repled: "Not Answered",
    call: "Missed",
    about: "Hi there",
    avatar: "images/b.jpg",
  ),
  CallModel(
    name: 'Shezad Dilawar',
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    time: '06:15',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    day: "Today",
    repled: "Answered",
    call: "Outgoing",
    about: "How's it going?",
    avatar: "images/c.jpg",
  ),
  CallModel(
    name: 'Asif',
    callType: CallModel.callRecived,
    time: '08:15',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    iconType: CallModel.Recived,
    day: "September 28, 2024",
    repled: "Answered",
    call: "Outgoing",
    about: "Let's catch up!",
    avatar: "images/d.jpg",
  ),
  CallModel(
    name: 'Ahmed',
    callType: CallModel.callRecived,
    time: '06:15',
    iconType: CallModel.Recived,
    day: "Today",
    repled: "Answered",
    call: "Outgoing",
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    about: "Missed your call",
    avatar: "images/no pic.png",
  ),
  CallModel(
    name: 'John',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '11:00',
    day: "September 27, 2024",
    repled: "Not Answered",
    call: "Missed",
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    about: "Call me back!",
    avatar: "images/no pic.png",
  ),
  CallModel(
    name: 'Sarah',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '08:30',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    day: "September 26, 2024",
    repled: "Not Answered",
    call: "Missed",
    about: "Busy right now",
    avatar: "images/no pic.png",
  ),
  CallModel(
    name: 'David',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '07:45',
    day: "Today",
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    repled: "Not Answered",
    call: "Missed",
    about: "Let's talk later",
    avatar: "images/no pic.png",
  ),
  CallModel(
    name: 'Haris',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '07:55',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    day: "September 29, 2024",
    repled: "Not Answered",
    call: "Missed",
    about: "Call you soon",
    avatar: "images/c.jpg",
  ),
  CallModel(
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    name: 'Zubaida Arif Madam',
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    time: '07:35',
    day: "September 28, 2024",
    repled: "Answered",
    call: "Outgoing",
    about: "Can we meet?",
    avatar: "images/maria-ivanova-lPjPMT8a37Y-unsplash.jpg",
  ),
  CallModel(
    name: 'Empty Call 1',
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    time: '',
    day: '',
    repled: '',
    call: '',
    about: '',
    avatar: '',
    i_call: '',
    i_repled: '',
    i_iconType: CallModel.Recived,
    i_time: '',
  ),
  CallModel(
    name: 'Asif',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    time: '08:15',
    day: "September 29, 2024",
    repled: "Answered",
    call: "Outgoing",
    about: "Let's connect!",
    avatar: "images/d.jpg",
  ),
  CallModel(
    name: 'Ahmed',
    callType: CallModel.callMissed,
    time: '06:15',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    iconType: CallModel.Missed,
    day: "September 26, 2024",
    repled: "Not Answered",
    call: "Missed",
    about: "Please call back",
    avatar: 'images/no pic.png',
  ),
  CallModel(
    name: 'John',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    callType: CallModel.callRecived,
    iconType: CallModel.Recived,
    time: '11:00',
    day: "Today",
    repled: "Answered",
    call: "Outgoing",
    about: "What time?",
    avatar: 'images/f.jpg',
  ),
  CallModel(
    name: 'Empty Call 2',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '',
    day: '',
    repled: '',
    call: '',
    about: '',
    avatar: '',
    i_call: '',
    i_repled: '',
    i_iconType: CallModel.Missed,
    i_time: '',
  ),
  CallModel(
    name: 'Sarah',
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '08:30',
    day: "September 27, 2024",
    repled: "Not Answered",
    call: "Missed",
    about: "Can't talk now",
    avatar: 'images/polina-lavor-G71Q0Wz8rcc-unsplash.jpg',
  ),
  CallModel(
    name: 'David',
    callType: CallModel.callMissed,
    iconType: CallModel.Missed,
    time: '07:45',
    day: "September 28, 2024",
    repled: "Not Answered",
    call: "Missed",
    i_call: "Not Answered",
    i_iconType: CallModel.Missed,
    i_repled: "missed",
    i_time: "10:00",
    about: "Need to reschedule",
    avatar: 'images/samsung-memory-ujDTFimW2mE-unsplash.jpg',
  ),
];
